package net.witerat.cafenatedsql.spi.mock;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MockPreparedStatment implements PreparedStatement {

//  private Connection connection;
  private String sql;
  
//  private int resultSetType;
//  private int resultSetConcurrency;
//  private int resultSetHoldability;
  private Logger logger = Logger.getLogger(this.getClass().getName());

  public MockPreparedStatment(final Connection connection0, final String sql0) {
//    this.connection = connection0;
    this.sql = sql0;
//    resultSetType = ResultSet.TYPE_FORWARD_ONLY;
//    resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
//    resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
  }

  public MockPreparedStatment(Connection connection0, String sql0, int resultSetType0,
      int resultSetConcurrency0, int resultSetHoldability0) {
//    this.connection = connection0;
    this.sql = sql0;
//    resultSetType = resultSetType0;
//    resultSetConcurrency = resultSetConcurrency0;
//    resultSetHoldability = resultSetHoldability0;
  }

  @Override
  public ResultSet executeQuery(String sql0) throws SQLException {
    logger.log(Level.INFO, "executeQuery:" + ((null!=sql0)?sql:this.sql));
    return null;
  }

  @Override
  public int executeUpdate(String sql0) throws SQLException {
    // No-op
    logger.log(Level.INFO, "executeUdpate:" + ((null!=sql0)?sql:this.sql));
    return 0;
  }

  @Override
  public void close() throws SQLException {
    // No-op

  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    // No-op

  }

  @Override
  public int getMaxRows() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    // No-op

  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    // No-op

  }

  @Override
  public int getQueryTimeout() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    // No-op

  }

  @Override
  public void cancel() throws SQLException {
    // No-op

  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public void clearWarnings() throws SQLException {
    // No-op

  }

  @Override
  public void setCursorName(String name) throws SQLException {
    // No-op

  }

  @Override
  public boolean execute(String sql) throws SQLException {
    // No-op
    return false;
  }

  @Override
  public ResultSet getResultSet() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public int getUpdateCount() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    // No-op
    return false;
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    // No-op

  }

  @Override
  public int getFetchDirection() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public void setFetchSize(int rows) throws SQLException {
    // No-op

  }

  @Override
  public int getFetchSize() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public int getResultSetType() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    // No-op

  }

  @Override
  public void clearBatch() throws SQLException {
    // No-op

  }

  @Override
  public int[] executeBatch() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public Connection getConnection() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    // No-op
    return false;
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    // No-op
    return false;
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    // No-op
    return false;
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    // No-op
    return false;
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public boolean isClosed() throws SQLException {
    // No-op
    return false;
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    // No-op

  }

  @Override
  public boolean isPoolable() throws SQLException {
    // No-op
    return false;
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    // No-op

  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    // No-op
    return false;
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    // No-op
    return null;
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    // No-op
    return false;
  }

  @Override
  public ResultSet executeQuery() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public int executeUpdate() throws SQLException {
    // No-op
    return 0;
  }

  @Override
  public void setNull(int parameterIndex, int sqlType) throws SQLException {
    // No-op

  }

  @Override
  public void setBoolean(int parameterIndex, boolean x) throws SQLException {
    // No-op

  }

  @Override
  public void setByte(int parameterIndex, byte x) throws SQLException {
    // No-op

  }

  @Override
  public void setShort(int parameterIndex, short x) throws SQLException {
    // No-op

  }

  @Override
  public void setInt(int parameterIndex, int x) throws SQLException {
    // No-op

  }

  @Override
  public void setLong(int parameterIndex, long x) throws SQLException {
    // No-op

  }

  @Override
  public void setFloat(int parameterIndex, float x) throws SQLException {
    // No-op

  }

  @Override
  public void setDouble(int parameterIndex, double x) throws SQLException {
    // No-op

  }

  @Override
  public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
    // No-op

  }

  @Override
  public void setString(int parameterIndex, String x) throws SQLException {
    // No-op

  }

  @Override
  public void setBytes(int parameterIndex, byte[] x) throws SQLException {
    // No-op

  }

  @Override
  public void setDate(int parameterIndex, Date x) throws SQLException {
    // No-op

  }

  @Override
  public void setTime(int parameterIndex, Time x) throws SQLException {
    // No-op

  }

  @Override
  public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
    // No-op

  }

  @Override
  public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
    // No-op

  }

  @Override
  public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
    // No-op

  }

  @Override
  public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
    // No-op

  }

  @Override
  public void clearParameters() throws SQLException {
    // No-op

  }

  @Override
  public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
    // No-op

  }

  @Override
  public void setObject(int parameterIndex, Object x) throws SQLException {
    // No-op

  }

  @Override
  public boolean execute() throws SQLException {
    // No-op
    return false;
  }

  @Override
  public void addBatch() throws SQLException {
    // No-op

  }

  @Override
  public void setCharacterStream(int parameterIndex, Reader reader, int length)
      throws SQLException {
    // No-op

  }

  @Override
  public void setRef(int parameterIndex, Ref x) throws SQLException {
    // No-op

  }

  @Override
  public void setBlob(int parameterIndex, Blob x) throws SQLException {
    // No-op

  }

  @Override
  public void setClob(int parameterIndex, Clob x) throws SQLException {
    // No-op

  }

  @Override
  public void setArray(int parameterIndex, Array x) throws SQLException {
    // No-op

  }

  @Override
  public ResultSetMetaData getMetaData() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
    // No-op

  }

  @Override
  public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
    // No-op

  }

  @Override
  public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
    // No-op

  }

  @Override
  public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
    // No-op

  }

  @Override
  public void setURL(int parameterIndex, URL x) throws SQLException {
    // No-op

  }

  @Override
  public ParameterMetaData getParameterMetaData() throws SQLException {
    // No-op
    return null;
  }

  @Override
  public void setRowId(int parameterIndex, RowId x) throws SQLException {
    // No-op

  }

  @Override
  public void setNString(int parameterIndex, String value) throws SQLException {
    // No-op

  }

  @Override
  public void setNCharacterStream(int parameterIndex, Reader value, long length)
      throws SQLException {
    // No-op

  }

  @Override
  public void setNClob(int parameterIndex, NClob value) throws SQLException {
    // No-op

  }

  @Override
  public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
    // No-op

  }

  @Override
  public void setBlob(int parameterIndex, InputStream inputStream, long length)
      throws SQLException {
    // No-op

  }

  @Override
  public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
    // No-op

  }

  @Override
  public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
    // No-op

  }

  @Override
  public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength)
      throws SQLException {
    // No-op

  }

  @Override
  public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
    // No-op

  }

  @Override
  public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
    // No-op

  }

  @Override
  public void setCharacterStream(int parameterIndex, Reader reader, long length)
      throws SQLException {
    // No-op

  }

  @Override
  public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
    // No-op

  }

  @Override
  public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
    // No-op

  }

  @Override
  public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
    // No-op

  }

  @Override
  public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
    // No-op

  }

  @Override
  public void setClob(int parameterIndex, Reader reader) throws SQLException {
    // No-op

  }

  @Override
  public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
    // No-op

  }

  @Override
  public void setNClob(int parameterIndex, Reader reader) throws SQLException {
    // No-op

  }

}
